-- =============================================================================
-- Модуль «Прогноз продаж с учётом мультиканальных маркетинговых активностей»
-- Структура новых таблиц (PostgreSQL 14+). Существующие таблицы гостиничной системы не затрагиваются:
-- модуль только добавляет собственные таблицы с префиксами mk_ (маркетинг) и fc_ (прогнозирование).
--
-- Серверная часть создаёт эти таблицы сама при запуске (spring.jpa.hibernate.ddl-auto=update), так что
-- запускать скрипт вручную не требуется. Он нужен для просмотра структуры, защиты проекта и установки
-- под управлением администратора БД. Скрипт можно выполнять повторно (IF NOT EXISTS).
--
--   psql -U postgres -d hotel -f docs/sql/forecast-schema.sql
-- =============================================================================

-- ---- Маркетинговые каналы (справочник) --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mk_channel (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(40)  NOT NULL UNIQUE,            -- латинский код канала: search, social, ...
    name        VARCHAR(100) NOT NULL,
    type        VARCHAR(20)  NOT NULL
                CHECK (type IN ('ONLINE_PAID', 'ONLINE_OWNED', 'PARTNER', 'OFFLINE')),
    description VARCHAR(300),
    active      BOOLEAN      NOT NULL,
    sort_order  INTEGER      NOT NULL
);

-- ---- Маркетинговые кампании (план и факт затрат; бюджет распределяется по дням периода равномерно) ----------
CREATE TABLE IF NOT EXISTS mk_campaign (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT         NOT NULL REFERENCES mk_channel (id),
    name       VARCHAR(150)   NOT NULL,
    start_date DATE           NOT NULL,
    end_date   DATE           NOT NULL,
    budget     NUMERIC(12, 2) NOT NULL,
    note       VARCHAR(500),
    created_by VARCHAR(50),
    created_at TIMESTAMP(6)   NOT NULL,
    CHECK (end_date >= start_date AND budget >= 0)
);
CREATE INDEX IF NOT EXISTS idx_mk_campaign_channel ON mk_campaign (channel_id);
CREATE INDEX IF NOT EXISTS idx_mk_campaign_period  ON mk_campaign (start_date, end_date);

-- ---- Фактические продажи по неделям (неделя начинается в понедельник) --------------------------------------
CREATE TABLE IF NOT EXISTS fc_sales_weekly (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start DATE           NOT NULL UNIQUE,
    bookings   INTEGER        NOT NULL,
    revenue    NUMERIC(14, 2) NOT NULL,
    source     VARCHAR(10)    NOT NULL CHECK (source IN ('DEMO', 'IMPORT', 'MANUAL')),
    updated_at TIMESTAMP(6)   NOT NULL,
    CHECK (bookings >= 0 AND revenue >= 0)
);

-- ---- Справочник алгоритмов прогнозирования (пополняется по ответу интеллектуального сервиса при обучении) ------
CREATE TABLE IF NOT EXISTS fc_algorithm (
    code           VARCHAR(40)  PRIMARY KEY,               -- seasonal_naive, holt_winters, mmm_ridge, gbm
    label          VARCHAR(100) NOT NULL,
    scenario_aware BOOLEAN      NOT NULL                   -- учитывает ли алгоритм маркетинговые затраты
);

-- ---- Реестр обученных моделей (сами артефакты хранит интеллектуальный сервис в зашифрованном виде) -----------
CREATE TABLE IF NOT EXISTS fc_model (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id      VARCHAR(64)  NOT NULL UNIQUE,         -- идентификатор в реестре интеллектуального сервиса
    target           VARCHAR(10)  NOT NULL CHECK (target IN ('REVENUE', 'BOOKINGS')),
    status           VARCHAR(10)  NOT NULL CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    algorithm        VARCHAR(40)  NOT NULL REFERENCES fc_algorithm (code),   -- победитель сравнения алгоритмов
    trained_at       TIMESTAMP(6) NOT NULL,
    trained_by       VARCHAR(50),
    data_from        DATE         NOT NULL,
    data_to          DATE         NOT NULL,             -- число недель ряда выводится из data_from и data_to
    data_fingerprint VARCHAR(64)  NOT NULL,                -- отпечаток данных обучения: по нему видно, что модель устарела
    cv_folds         INTEGER      NOT NULL,
    cv_horizon       INTEGER      NOT NULL,
    interval_level   DOUBLE PRECISION NOT NULL,
    wape             DOUBLE PRECISION,
    mape             DOUBLE PRECISION,
    smape            DOUBLE PRECISION,
    rmse             DOUBLE PRECISION,
    bias             DOUBLE PRECISION
);

-- ---- Сравнение алгоритмов (таблица лидеров) для каждой модели ---------------------------------------------
CREATE TABLE IF NOT EXISTS fc_model_candidate (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id       BIGINT       NOT NULL REFERENCES fc_model (id),
    algorithm      VARCHAR(40)  NOT NULL REFERENCES fc_algorithm (code),
    selected       BOOLEAN      NOT NULL,
    wape           DOUBLE PRECISION,
    mape           DOUBLE PRECISION,
    rmse           DOUBLE PRECISION,
    skill_vs_naive DOUBLE PRECISION,                       -- выигрыш по WAPE у сезонной наивной модели
    skipped_reason VARCHAR(300),
    UNIQUE (model_id, algorithm)
);

-- ---- Параметры и вклад каналов в модели -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fc_model_channel_effect (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id           BIGINT           NOT NULL REFERENCES fc_model (id),
    channel_id         BIGINT           NOT NULL REFERENCES mk_channel (id),
    adstock_decay      DOUBLE PRECISION NOT NULL,          -- доля эффекта, переходящая на следующую неделю
    saturation_scale   DOUBLE PRECISION NOT NULL,          -- затраты, при которых отдача заметно убывает
    max_effect         DOUBLE PRECISION NOT NULL,
    total_spend        DOUBLE PRECISION NOT NULL,          -- средние недельные затраты и возврат на 1 $ выводятся из итогов
    active_weeks       INTEGER          NOT NULL,
    spend_cv           DOUBLE PRECISION NOT NULL,          -- изменчивость затрат: при малой эффект канала не определяется надёжно
    contribution_total DOUBLE PRECISION NOT NULL,
    contribution_share DOUBLE PRECISION NOT NULL,
    marginal_roi       DOUBLE PRECISION,
    saturation_level   DOUBLE PRECISION NOT NULL,
    low_variation      BOOLEAN          NOT NULL,           -- вывод интеллектуального сервиса о достоверности оценки канала
    UNIQUE (model_id, channel_id)
);

-- ---- Проверка вне выборки (скользящая проверка на неделях, которые модель не видела) -----------------------
CREATE TABLE IF NOT EXISTS fc_model_backtest_point (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id   BIGINT           NOT NULL REFERENCES fc_model (id),
    week_start DATE             NOT NULL,
    actual     DOUBLE PRECISION NOT NULL,
    predicted  DOUBLE PRECISION NOT NULL,
    lower      DOUBLE PRECISION NOT NULL,
    upper      DOUBLE PRECISION NOT NULL
);

-- ---- Предупреждения, выданные при обучении -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fc_model_warning (
    model_id   BIGINT       NOT NULL REFERENCES fc_model (id),
    "position" INTEGER      NOT NULL,
    message    VARCHAR(500) NOT NULL,
    PRIMARY KEY (model_id, "position")
);
